async function request(path, options = {}) {
  const response = await fetch(path, {
    ...options,
    headers: options.body ? { "content-type": "application/json", ...options.headers } : options.headers
  });
  const contentType = response.headers.get("content-type") || "";
  const result = contentType.includes("application/json") ? await response.json() : await response.text();
  if (!response.ok) throw new Error(result?.error?.message || `Request failed: ${response.status}`);
  return result;
}

export const api = {
  health: () => request("/api/health"),
  providerSettings: () => request("/api/settings/providers"),
  updateProviderSettings: (input) => request("/api/settings/providers", { method: "PUT", body: JSON.stringify(input) }),
  projects: () => request("/api/projects"),
  createProject: (title) => request("/api/projects", { method: "POST", body: JSON.stringify({ title }) }),
  project: (projectId) => request(`/api/projects/${projectId}`),
  updateProject: (projectId, input) => request(`/api/projects/${projectId}`, { method: "PATCH", body: JSON.stringify(input) }),
  createCanvas: (projectId, title) => request(`/api/projects/${projectId}/canvases`, { method: "POST", body: JSON.stringify({ title }) }),
  canvas: (projectId, canvasId) => request(`/api/projects/${projectId}/canvases/${canvasId}`),
  createNode: (projectId, canvasId, input) => request(`/api/projects/${projectId}/canvases/${canvasId}/nodes`, { method: "POST", body: JSON.stringify(input) }),
  restoreNode: (projectId, canvasId, input) => request(`/api/projects/${projectId}/canvases/${canvasId}/nodes/restore`, { method: "POST", body: JSON.stringify(input) }),
  updateNode: (projectId, nodeId, input) => request(`/api/projects/${projectId}/nodes/${nodeId}`, { method: "PATCH", body: JSON.stringify(input) }),
  composeGrid: (projectId, nodeId, input = {}) => request(`/api/projects/${projectId}/nodes/${nodeId}/grid/compose`, { method: "POST", body: JSON.stringify(input) }),
  saveImageEditResult: (projectId, nodeId, input) => request(`/api/projects/${projectId}/nodes/${nodeId}/image-edit/result`, { method: "POST", body: JSON.stringify(input) }),
  nodePrompt: (projectId, nodeId) => request(`/api/projects/${projectId}/nodes/${nodeId}/prompt`),
  saveNodePrompt: (projectId, nodeId, input) => request(`/api/projects/${projectId}/nodes/${nodeId}/prompt`, { method: "PUT", body: JSON.stringify(input) }),
  script: (projectId, nodeId) => request(`/api/projects/${projectId}/scripts/${nodeId}`),
  createScriptRow: (projectId, nodeId, input) => request(`/api/projects/${projectId}/scripts/${nodeId}/rows`, { method: "POST", body: JSON.stringify(input) }),
  updateScriptRow: (projectId, nodeId, rowId, input) => request(`/api/projects/${projectId}/scripts/${nodeId}/rows/${rowId}`, { method: "PATCH", body: JSON.stringify(input) }),
  deleteScriptRow: (projectId, nodeId, rowId) => request(`/api/projects/${projectId}/scripts/${nodeId}/rows/${rowId}`, { method: "DELETE" }),
  modelCapabilities: () => request("/api/model-capabilities?capability=video"),
  cinematicProductions: (projectId) => request(`/api/projects/${projectId}/cinematic-productions`),
  createCinematicProduction: (projectId, input) => request(`/api/projects/${projectId}/cinematic-productions`, { method: "POST", body: JSON.stringify(input) }),
  cinematicProduction: (projectId, productionId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}`),
  updateCinematicProduction: (projectId, productionId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}`, { method: "PATCH", body: JSON.stringify(input) }),
  storyPacket: (projectId, productionId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/story-packet`),
  saveStoryPacket: (projectId, productionId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/story-packet`, { method: "PUT", body: JSON.stringify(input) }),
  visualBible: (projectId, productionId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/visual-bible`),
  saveVisualBible: (projectId, productionId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/visual-bible`, { method: "PUT", body: JSON.stringify(input) }),
  assetAuthorities: (projectId, productionId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/asset-authorities`),
  searchAssetAuthorities: (projectId, productionId, input = {}) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/asset-authorities/search`, { method: "POST", body: JSON.stringify(input) }),
  batchTransitionAssetAuthorities: (projectId, productionId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/asset-authorities/batch-transition`, { method: "POST", body: JSON.stringify(input) }),
  deriveAssetAuthorities: (projectId, productionId, input = {}) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/asset-authorities/derive`, { method: "POST", body: JSON.stringify(input) }),
  assetAuthorityVersions: (projectId, productionId, authorityId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/asset-authorities/${authorityId}/versions`),
  assetAuthorityImpact: (projectId, productionId, authorityId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/asset-authorities/${authorityId}/impact`),
  restoreAssetAuthorityVersion: (projectId, productionId, authorityId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/asset-authorities/${authorityId}/restore`, { method: "POST", body: JSON.stringify(input) }),
  createAssetAuthority: (projectId, productionId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/asset-authorities`, { method: "POST", body: JSON.stringify(input) }),
  updateAssetAuthority: (projectId, productionId, authorityId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/asset-authorities/${authorityId}`, { method: "PATCH", body: JSON.stringify(input) }),
  bindCharacterVoiceProfile: (projectId, productionId, authorityId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/asset-authorities/${authorityId}/voice-profile`, { method: "POST", body: JSON.stringify(input) }),
  routeAssetAuthorityRisk: (projectId, productionId, input = {}) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/asset-authorities/route-risk`, { method: "POST", body: JSON.stringify(input) }),
  compileAssetAuthority: (projectId, productionId, authorityId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/asset-authorities/${authorityId}/compile`, { method: "POST", body: JSON.stringify(input) }),
  compileStoryboardPrompt: (projectId, productionId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboard-prompts/compile`, { method: "POST", body: JSON.stringify(input) }),
  storyboards: (projectId, productionId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards`),
  createStoryboard: (projectId, productionId, input = {}) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards`, { method: "POST", body: JSON.stringify(input) }),
  storyboard: (projectId, productionId, storyboardId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards/${storyboardId}`),
  reorderStoryboard: (projectId, productionId, storyboardId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards/${storyboardId}/order`, { method: "PUT", body: JSON.stringify(input) }),
  storyboardVersions: (projectId, productionId, storyboardId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards/${storyboardId}/versions`),
  storyboardShotVersions: (projectId, productionId, storyboardId, storyboardShotId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards/${storyboardId}/shots/${storyboardShotId}/versions`),
  compareStoryboardShotVersions: (projectId, productionId, storyboardId, storyboardShotId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards/${storyboardId}/shots/${storyboardShotId}/compare`, { method: "POST", body: JSON.stringify(input) }),
  storyboardBatchJobs: (projectId, productionId, storyboardId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards/${storyboardId}/batches`),
  createStoryboardBatchJob: (projectId, productionId, storyboardId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards/${storyboardId}/batches`, { method: "POST", body: JSON.stringify(input) }),
  advanceStoryboardBatchJob: (projectId, productionId, storyboardId, jobId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards/${storyboardId}/batches/${jobId}/advance`, { method: "POST", body: "{}" }),
  cancelStoryboardBatchJob: (projectId, productionId, storyboardId, jobId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards/${storyboardId}/batches/${jobId}/cancel`, { method: "POST", body: "{}" }),
  retryStoryboardBatchItem: (projectId, productionId, storyboardId, jobId, itemId, input = {}) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards/${storyboardId}/batches/${jobId}/items/${itemId}/retry`, { method: "POST", body: JSON.stringify(input) }),
  updateStoryboardShot: (projectId, productionId, storyboardId, storyboardShotId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards/${storyboardId}/shots/${storyboardShotId}`, { method: "PATCH", body: JSON.stringify(input) }),
  setStoryboardShotMedia: (projectId, productionId, storyboardId, storyboardShotId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards/${storyboardId}/shots/${storyboardShotId}/media`, { method: "PUT", body: JSON.stringify(input) }),
  setStoryboardVideoReference: (projectId, productionId, storyboardId, storyboardShotId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards/${storyboardId}/shots/${storyboardShotId}/video-reference`, { method: "PUT", body: JSON.stringify(input) }),
  storyboardVideoReferences: (projectId, productionId, storyboardId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards/${storyboardId}/video-references`),
  importStoryboardToTimeline: (projectId, productionId, storyboardId, input = {}) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards/${storyboardId}/import-timeline`, { method: "POST", body: JSON.stringify(input) }),
  cinematicShots: (projectId, productionId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/shots`),
  createCinematicShot: (projectId, productionId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/shots`, { method: "POST", body: JSON.stringify(input) }),
  updateCinematicShot: (projectId, productionId, shotId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/shots/${shotId}`, { method: "PATCH", body: JSON.stringify(input) }),
  generationUnits: (projectId, productionId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/generation-units`),
  createGenerationUnit: (projectId, productionId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/generation-units`, { method: "POST", body: JSON.stringify(input) }),
  updateGenerationUnit: (projectId, productionId, unitId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/generation-units/${unitId}`, { method: "PATCH", body: JSON.stringify(input) }),
  compileGenerationUnit: (projectId, productionId, unitId, input = {}) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/generation-units/${unitId}/compile`, { method: "POST", body: JSON.stringify(input) }),
  preflightGenerationUnit: (projectId, productionId, unitId, input = {}) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/generation-units/${unitId}/preflight`, { method: "POST", body: JSON.stringify(input) }),
  runGenerationUnit: (projectId, productionId, unitId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/generation-units/${unitId}/runs`, { method: "POST", body: JSON.stringify({ billingMode: "provider_account", ...input }) }),
  cinematicEvaluations: (projectId, productionId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/evaluations`),
  sequencePrevis: (projectId, productionId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/sequence-previs`),
  saveSequencePrevis: (projectId, productionId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/sequence-previs`, { method: "POST", body: JSON.stringify(input) }),
  updateSequencePrevis: (projectId, productionId, previsId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/sequence-previs/${previsId}`, { method: "PATCH", body: JSON.stringify(input) }),
  reviewSequencePrevis: (projectId, productionId, previsId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/sequence-previs/${previsId}/reviews`, { method: "POST", body: JSON.stringify(input) }),
  recordSequencePrevisPlayback: (projectId, productionId, previsId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/sequence-previs/${previsId}/playback-receipts`, { method: "POST", body: JSON.stringify(input) }),
  compileVisualContext: (projectId, productionId, previsId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/sequence-previs/${previsId}/visual-context`, { method: "POST", body: JSON.stringify(input) }),
  visualContextBundles: (projectId, productionId, shotId = "") => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/visual-context-bundles${shotId ? `?shotId=${encodeURIComponent(shotId)}` : ""}`),
  visualTakeMemories: (projectId, productionId, unitId = "") => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/visual-take-memories${unitId ? `?generationUnitId=${encodeURIComponent(unitId)}` : ""}`),
  creativeDecisionTraces: (projectId, productionId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/creative-decision-traces`),
  addReview: (projectId, input) => request(`/api/projects/${projectId}/reviews`, { method: "POST", body: JSON.stringify(input) }),
  assetAuthorityAggregates: (projectId, productionId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/asset-authority-aggregates`),
  assetAuthorityAggregate: (projectId, productionId, authorityId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/asset-authorities/${authorityId}/aggregate`),
  addCinematicEvaluation: (projectId, productionId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/evaluations`, { method: "POST", body: JSON.stringify(input) }),
  professionalContributions: (projectId, productionId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/contributions`),
  deleteNode: (projectId, nodeId) => request(`/api/projects/${projectId}/nodes/${nodeId}`, { method: "DELETE" }),
  runNode: (projectId, nodeId, input) => request(`/api/projects/${projectId}/nodes/${nodeId}/run`, { method: "POST", body: JSON.stringify(input) }),
  pollRun: (projectId, runId) => request(`/api/projects/${projectId}/runs/${runId}/poll`, { method: "POST" }),
  runs: (projectId) => request(`/api/projects/${projectId}/runs`),
  connect: (projectId, input) => request(`/api/projects/${projectId}/edges`, { method: "POST", body: JSON.stringify(input) }),
  deleteEdge: (projectId, edgeId) => request(`/api/projects/${projectId}/edges/${edgeId}`, { method: "DELETE" }),
  createGroup: (projectId, input) => request(`/api/projects/${projectId}/groups`, { method: "POST", body: JSON.stringify(input) }),
  addGroupMember: (projectId, groupId, nodeId) => request(`/api/projects/${projectId}/groups/${groupId}/members`, { method: "POST", body: JSON.stringify({ nodeId }) }),
  deleteGroup: (projectId, groupId) => request(`/api/projects/${projectId}/groups/${groupId}`, { method: "DELETE" }),
  importMedia: (projectId, input) => request(`/api/projects/${projectId}/media/import`, { method: "POST", body: JSON.stringify(input) }),
  importDataMedia: (projectId, input) => request(`/api/projects/${projectId}/media/data`, { method: "POST", body: JSON.stringify(input) }),
  publishMedia: (projectId, mediaId, input = {}) => request(`/api/projects/${projectId}/media/${mediaId}/publish`, { method: "POST", body: JSON.stringify(input) }),
  prepareMedia: (projectId, mediaId, input = {}) => request(`/api/projects/${projectId}/media/${mediaId}/prepare`, { method: "POST", body: JSON.stringify(input) }),
  mediaPreparation: (projectId, mediaId) => request(`/api/projects/${projectId}/media/${mediaId}/preparation`),
  workflow: (projectId) => request(`/api/projects/${projectId}/workflow`),
  setLayer: (projectId, layer, input) => request(`/api/projects/${projectId}/workflow/${layer}`, { method: "PUT", body: JSON.stringify(input) }),
  director: (projectId, nodeId) => request(`/api/projects/${projectId}/director/${nodeId}`),
  saveDirector: (projectId, nodeId, stage) => request(`/api/projects/${projectId}/director/${nodeId}`, { method: "PUT", body: JSON.stringify({ stage }) }),
  applyDirectorCommand: (projectId, nodeId, command) => request(`/api/projects/${projectId}/director/${nodeId}/commands`, { method: "POST", body: JSON.stringify({ command }) }),
  bindDirectorWorld: (projectId, nodeId, input) => request(`/api/projects/${projectId}/director/${nodeId}/world-environment`, { method: "POST", body: JSON.stringify(input) }),
  panorama: (projectId, nodeId) => request(`/api/projects/${projectId}/panoramas/${nodeId}`),
  setPanorama: (projectId, nodeId, input) => request(`/api/projects/${projectId}/panoramas/${nodeId}`, { method: "PUT", body: JSON.stringify(input) }),
  createTimeline: (projectId, title) => request(`/api/projects/${projectId}/timelines`, { method: "POST", body: JSON.stringify({ title }) }),
  timelines: (projectId) => request(`/api/projects/${projectId}/timelines`),
  timeline: (projectId, timelineId) => request(`/api/projects/${projectId}/timelines/${timelineId}`),
  addClip: (projectId, timelineId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips`, { method: "POST", body: JSON.stringify(input) }),
  moveTimelineClip: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}/move`, { method: "POST", body: JSON.stringify(input) }),
  trimTimelineClip: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}/trim`, { method: "POST", body: JSON.stringify(input) }),
  updateTimelineClip: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}`, { method: "PATCH", body: JSON.stringify(input) }),
  splitTimelineClip: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}/split`, { method: "POST", body: JSON.stringify(input) }),
  rippleTimelineClip: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}/ripple`, { method: "POST", body: JSON.stringify(input) }),
  slipTimelineClip: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}/slip`, { method: "POST", body: JSON.stringify(input) }),
  snapTimelineClip: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}/snap`, { method: "POST", body: JSON.stringify(input) }),
  undoTimelineEdit: (projectId, timelineId) => request(`/api/projects/${projectId}/timelines/${timelineId}/undo`, { method: "POST" }),
  redoTimelineEdit: (projectId, timelineId) => request(`/api/projects/${projectId}/timelines/${timelineId}/redo`, { method: "POST" }),
  undoTimelineResourceEdit: (projectId, timelineId) => request(`/api/projects/${projectId}/timelines/${timelineId}/resource-undo`, { method: "POST" }),
  redoTimelineResourceEdit: (projectId, timelineId) => request(`/api/projects/${projectId}/timelines/${timelineId}/resource-redo`, { method: "POST" }),
  addTimelineTrack: (projectId, timelineId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/tracks`, { method: "POST", body: JSON.stringify(input) }),
  updateTimelineTrack: (projectId, timelineId, trackId, patch) => request(`/api/projects/${projectId}/timelines/${timelineId}/tracks/${trackId}`, { method: "PATCH", body: JSON.stringify(patch) }),
  removeTimelineTrack: (projectId, timelineId, trackId) => request(`/api/projects/${projectId}/timelines/${timelineId}/tracks/${trackId}`, { method: "DELETE" }),
  reorderTimelineTracks: (projectId, timelineId, trackIds) => request(`/api/projects/${projectId}/timelines/${timelineId}/tracks/reorder`, { method: "POST", body: JSON.stringify({ trackIds }) }),
  addTimelineTransition: (projectId, timelineId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/transitions`, { method: "POST", body: JSON.stringify(input) }),
  updateTimelineTransition: (projectId, timelineId, transitionId, patch) => request(`/api/projects/${projectId}/timelines/${timelineId}/transitions/${transitionId}`, { method: "PATCH", body: JSON.stringify(patch) }),
  removeTimelineTransition: (projectId, timelineId, transitionId) => request(`/api/projects/${projectId}/timelines/${timelineId}/transitions/${transitionId}`, { method: "DELETE" }),
  addTimelineEffect: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}/effects`, { method: "POST", body: JSON.stringify(input) }),
  updateTimelineEffect: (projectId, timelineId, effectId, patch) => request(`/api/projects/${projectId}/timelines/${timelineId}/effects/${effectId}`, { method: "PATCH", body: JSON.stringify(patch) }),
  removeTimelineEffect: (projectId, timelineId, effectId) => request(`/api/projects/${projectId}/timelines/${timelineId}/effects/${effectId}`, { method: "DELETE" }),
  addTimelineMarker: (projectId, timelineId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/markers`, { method: "POST", body: JSON.stringify(input) }),
  updateTimelineMarker: (projectId, timelineId, markerId, patch) => request(`/api/projects/${projectId}/timelines/${timelineId}/markers/${markerId}`, { method: "PATCH", body: JSON.stringify(patch) }),
  removeTimelineMarker: (projectId, timelineId, markerId) => request(`/api/projects/${projectId}/timelines/${timelineId}/markers/${markerId}`, { method: "DELETE" }),
  addTimelineKeyframe: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}/keyframes`, { method: "POST", body: JSON.stringify(input) }),
  updateTimelineKeyframe: (projectId, timelineId, keyframeId, patch) => request(`/api/projects/${projectId}/timelines/${timelineId}/keyframes/${keyframeId}`, { method: "PATCH", body: JSON.stringify(patch) }),
  removeTimelineKeyframe: (projectId, timelineId, keyframeId) => request(`/api/projects/${projectId}/timelines/${timelineId}/keyframes/${keyframeId}`, { method: "DELETE" }),
  createRenderJob: (projectId, timelineId, input = {}) => request(`/api/projects/${projectId}/timelines/${timelineId}/render-jobs`, { method: "POST", body: JSON.stringify(input) }),
  renderJobs: (projectId, timelineId = "") => request(`/api/projects/${projectId}/render-jobs${timelineId ? `?timelineId=${encodeURIComponent(timelineId)}` : ""}`),
  renderJob: (projectId, renderJobId) => request(`/api/projects/${projectId}/render-jobs/${renderJobId}`),
  renderJobQc: (projectId, renderJobId) => request(`/api/projects/${projectId}/render-jobs/${renderJobId}/qc`),
  createDeliveryPackage: (projectId, renderJobId, input = {}) => request(`/api/projects/${projectId}/render-jobs/${renderJobId}/delivery-packages`, { method: "POST", body: JSON.stringify(input) }),
  deliveryPackages: (projectId, renderJobId = "") => request(`/api/projects/${projectId}/delivery-packages${renderJobId ? `?renderJobId=${encodeURIComponent(renderJobId)}` : ""}`),
  cancelRenderJob: (projectId, renderJobId) => request(`/api/projects/${projectId}/render-jobs/${renderJobId}/cancel`, { method: "POST", body: "{}" }),
  resumeRenderJob: (projectId, renderJobId) => request(`/api/projects/${projectId}/render-jobs/${renderJobId}/resume`, { method: "POST", body: "{}" }),
  reviews: (projectId) => request(`/api/projects/${projectId}/reviews`),
  assets: (projectId) => request(`/api/projects/${projectId}/assets`),
  createAsset: (projectId, input) => request(`/api/projects/${projectId}/assets`, { method: "POST", body: JSON.stringify(input) }),
  addAssetVersion: (projectId, assetId, input) => request(`/api/projects/${projectId}/assets/${assetId}/versions`, { method: "POST", body: JSON.stringify(input) }),
  controlSession: (projectId) => request(`/api/projects/${projectId}/control-session`),
  automationRuns: (projectId) => request(`/api/projects/${projectId}/automation-runs`),
  cinematicWorkflowStatus: (projectId) => request(`/api/projects/${projectId}/cinematic-workflow/status`),
  startCinematicWorkflow: (projectId, input = {}) => request(`/api/projects/${projectId}/cinematic-workflow/start`, { method: "POST", body: JSON.stringify(input) }),
  agentProfiles: (projectId) => request(`/api/projects/${projectId}/agent-profiles`),
  automationTasks: (projectId, runId) => request(`/api/projects/${projectId}/automation-runs/${runId}/tasks`),
  automationActivities: (projectId, runId) => request(`/api/projects/${projectId}/automation-runs/${runId}/activities`),
  startAutomation: (projectId, input = {}) => request(`/api/projects/${projectId}/automation-runs`, { method: "POST", body: JSON.stringify(input) }),
  pauseAutomation: (projectId, runId, input = {}) => request(`/api/projects/${projectId}/automation-runs/${runId}/pause`, { method: "POST", body: JSON.stringify(input) }),
  resumeAutomation: (projectId, runId, input = {}) => request(`/api/projects/${projectId}/automation-runs/${runId}/resume`, { method: "POST", body: JSON.stringify(input) }),
  cancelAutomation: (projectId, runId, input = {}) => request(`/api/projects/${projectId}/automation-runs/${runId}/cancel`, { method: "POST", body: JSON.stringify(input) }),
  takeoverAutomation: (projectId, runId, input = {}) => request(`/api/projects/${projectId}/automation-runs/${runId}/takeover`, { method: "POST", body: JSON.stringify(input) }),
  exitAutomation: (projectId, runId, input = {}) => request(`/api/projects/${projectId}/automation-runs/${runId}/exit`, { method: "POST", body: JSON.stringify(input) }),
  advanceAutomation: (projectId, runId) => request(`/api/projects/${projectId}/automation-runs/${runId}/advance`, { method: "POST", body: "{}" }),
  retryAutomationTask: (projectId, runId, taskId, input = {}) => request(`/api/projects/${projectId}/automation-runs/${runId}/tasks/${taskId}/retry`, { method: "POST", body: JSON.stringify(input) }),
  budgetGrant: (projectId) => request(`/api/projects/${projectId}/budget-grant`),
  saveBudgetGrant: (projectId, input) => request(`/api/projects/${projectId}/budget-grant`, { method: "PUT", body: JSON.stringify(input) }),
  budgetReservations: (projectId, automationRunId = "") => request(`/api/projects/${projectId}/budget-reservations${automationRunId ? `?automationRunId=${encodeURIComponent(automationRunId)}` : ""}`),
  reserveBudget: (projectId, input) => request(`/api/projects/${projectId}/budget-reservations`, { method: "POST", body: JSON.stringify(input) }),
  consumeBudgetReservation: (projectId, reservationId, input = {}) => request(`/api/projects/${projectId}/budget-reservations/${reservationId}/consume`, { method: "POST", body: JSON.stringify(input) }),
  reconcileBudgetReservation: (projectId, reservationId, input) => request(`/api/projects/${projectId}/budget-reservations/${reservationId}/reconcile`, { method: "POST", body: JSON.stringify(input) }),
  releaseBudgetReservation: (projectId, reservationId) => request(`/api/projects/${projectId}/budget-reservations/${reservationId}/release`, { method: "POST", body: "{}" })
};
