async function request(path, options = {}) {
  const response = await fetch(path, {
    ...options,
    headers: options.body ? { "content-type": "application/json", ...options.headers } : options.headers
  });
  const contentType = response.headers.get("content-type") || "";
  const result = contentType.includes("application/json") ? await response.json() : await response.text();
  if (!response.ok) throw new Error(result?.error?.message || `Request failed: ${response.status}`);
  return result;
}

export const api = {
  health: () => request("/api/health"),
  providerSettings: () => request("/api/settings/providers"),
  updateProviderSettings: (input) => request("/api/settings/providers", { method: "PUT", body: JSON.stringify(input) }),
  projects: () => request("/api/projects"),
  createProject: (title) => request("/api/projects", { method: "POST", body: JSON.stringify({ title }) }),
  project: (projectId) => request(`/api/projects/${projectId}`),
  updateProject: (projectId, input) => request(`/api/projects/${projectId}`, { method: "PATCH", body: JSON.stringify(input) }),
  canvas: (projectId, canvasId) => request(`/api/projects/${projectId}/canvases/${canvasId}`),
  createNode: (projectId, canvasId, input) => request(`/api/projects/${projectId}/canvases/${canvasId}/nodes`, { method: "POST", body: JSON.stringify(input) }),
  restoreNode: (projectId, canvasId, input) => request(`/api/projects/${projectId}/canvases/${canvasId}/nodes/restore`, { method: "POST", body: JSON.stringify(input) }),
  updateNode: (projectId, nodeId, input) => request(`/api/projects/${projectId}/nodes/${nodeId}`, { method: "PATCH", body: JSON.stringify(input) }),
  composeGrid: (projectId, nodeId, input = {}) => request(`/api/projects/${projectId}/nodes/${nodeId}/grid/compose`, { method: "POST", body: JSON.stringify(input) }),
  saveImageEditResult: (projectId, nodeId, input) => request(`/api/projects/${projectId}/nodes/${nodeId}/image-edit/result`, { method: "POST", body: JSON.stringify(input) }),
  nodePrompt: (projectId, nodeId) => request(`/api/projects/${projectId}/nodes/${nodeId}/prompt`),
  saveNodePrompt: (projectId, nodeId, input) => request(`/api/projects/${projectId}/nodes/${nodeId}/prompt`, { method: "PUT", body: JSON.stringify(input) }),
  script: (projectId, nodeId) => request(`/api/projects/${projectId}/scripts/${nodeId}`),
  storyPacket: (projectId, productionId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/story-packet`),
  bindCharacterVoiceProfile: (projectId, productionId, authorityId, input) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/asset-authorities/${authorityId}/voice-profile`, { method: "POST", body: JSON.stringify(input) }),
  storyboard: (projectId, productionId, storyboardId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/storyboards/${storyboardId}`),
  assetAuthorityAggregates: (projectId, productionId) => request(`/api/projects/${projectId}/cinematic-productions/${productionId}/asset-authority-aggregates`),
  deleteNode: (projectId, nodeId) => request(`/api/projects/${projectId}/nodes/${nodeId}`, { method: "DELETE" }),
  runNode: (projectId, nodeId, input) => request(`/api/projects/${projectId}/nodes/${nodeId}/run`, { method: "POST", body: JSON.stringify(input) }),
  pollRun: (projectId, runId) => request(`/api/projects/${projectId}/runs/${runId}/poll`, { method: "POST" }),
  runs: (projectId) => request(`/api/projects/${projectId}/runs`),
  connect: (projectId, input) => request(`/api/projects/${projectId}/edges`, { method: "POST", body: JSON.stringify(input) }),
  deleteEdge: (projectId, edgeId) => request(`/api/projects/${projectId}/edges/${edgeId}`, { method: "DELETE" }),
  createGroup: (projectId, input) => request(`/api/projects/${projectId}/groups`, { method: "POST", body: JSON.stringify(input) }),
  addGroupMember: (projectId, groupId, nodeId) => request(`/api/projects/${projectId}/groups/${groupId}/members`, { method: "POST", body: JSON.stringify({ nodeId }) }),
  deleteGroup: (projectId, groupId) => request(`/api/projects/${projectId}/groups/${groupId}`, { method: "DELETE" }),
  importMedia: (projectId, input) => request(`/api/projects/${projectId}/media/import`, { method: "POST", body: JSON.stringify(input) }),
  importDataMedia: (projectId, input) => request(`/api/projects/${projectId}/media/data`, { method: "POST", body: JSON.stringify(input) }),
  prepareMedia: (projectId, mediaId, input = {}) => request(`/api/projects/${projectId}/media/${mediaId}/prepare`, { method: "POST", body: JSON.stringify(input) }),
  mediaPreparation: (projectId, mediaId) => request(`/api/projects/${projectId}/media/${mediaId}/preparation`),
  workflow: (projectId) => request(`/api/projects/${projectId}/workflow`),
  director: (projectId, nodeId) => request(`/api/projects/${projectId}/director/${nodeId}`),
  applyDirectorCommand: (projectId, nodeId, command) => request(`/api/projects/${projectId}/director/${nodeId}/commands`, { method: "POST", body: JSON.stringify({ command }) }),
  panorama: (projectId, nodeId) => request(`/api/projects/${projectId}/panoramas/${nodeId}`),
  createTimeline: (projectId, title) => request(`/api/projects/${projectId}/timelines`, { method: "POST", body: JSON.stringify({ title }) }),
  timelines: (projectId) => request(`/api/projects/${projectId}/timelines`),
  timeline: (projectId, timelineId) => request(`/api/projects/${projectId}/timelines/${timelineId}`),
  addClip: (projectId, timelineId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips`, { method: "POST", body: JSON.stringify(input) }),
  moveTimelineClip: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}/move`, { method: "POST", body: JSON.stringify(input) }),
  updateTimelineClip: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}`, { method: "PATCH", body: JSON.stringify(input) }),
  splitTimelineClip: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}/split`, { method: "POST", body: JSON.stringify(input) }),
  rippleTimelineClip: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}/ripple`, { method: "POST", body: JSON.stringify(input) }),
  slipTimelineClip: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}/slip`, { method: "POST", body: JSON.stringify(input) }),
  snapTimelineClip: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}/snap`, { method: "POST", body: JSON.stringify(input) }),
  undoTimelineEdit: (projectId, timelineId) => request(`/api/projects/${projectId}/timelines/${timelineId}/undo`, { method: "POST" }),
  redoTimelineEdit: (projectId, timelineId) => request(`/api/projects/${projectId}/timelines/${timelineId}/redo`, { method: "POST" }),
  undoTimelineResourceEdit: (projectId, timelineId) => request(`/api/projects/${projectId}/timelines/${timelineId}/resource-undo`, { method: "POST" }),
  redoTimelineResourceEdit: (projectId, timelineId) => request(`/api/projects/${projectId}/timelines/${timelineId}/resource-redo`, { method: "POST" }),
  addTimelineTrack: (projectId, timelineId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/tracks`, { method: "POST", body: JSON.stringify(input) }),
  updateTimelineTrack: (projectId, timelineId, trackId, patch) => request(`/api/projects/${projectId}/timelines/${timelineId}/tracks/${trackId}`, { method: "PATCH", body: JSON.stringify(patch) }),
  removeTimelineTrack: (projectId, timelineId, trackId) => request(`/api/projects/${projectId}/timelines/${timelineId}/tracks/${trackId}`, { method: "DELETE" }),
  reorderTimelineTracks: (projectId, timelineId, trackIds) => request(`/api/projects/${projectId}/timelines/${timelineId}/tracks/reorder`, { method: "POST", body: JSON.stringify({ trackIds }) }),
  addTimelineTransition: (projectId, timelineId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/transitions`, { method: "POST", body: JSON.stringify(input) }),
  addTimelineEffect: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}/effects`, { method: "POST", body: JSON.stringify(input) }),
  addTimelineMarker: (projectId, timelineId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/markers`, { method: "POST", body: JSON.stringify(input) }),
  addTimelineKeyframe: (projectId, timelineId, clipId, input) => request(`/api/projects/${projectId}/timelines/${timelineId}/clips/${clipId}/keyframes`, { method: "POST", body: JSON.stringify(input) }),
  createRenderJob: (projectId, timelineId, input = {}) => request(`/api/projects/${projectId}/timelines/${timelineId}/render-jobs`, { method: "POST", body: JSON.stringify(input) }),
  renderJobs: (projectId, timelineId = "") => request(`/api/projects/${projectId}/render-jobs${timelineId ? `?timelineId=${encodeURIComponent(timelineId)}` : ""}`),
  renderJobQc: (projectId, renderJobId) => request(`/api/projects/${projectId}/render-jobs/${renderJobId}/qc`),
  createDeliveryPackage: (projectId, renderJobId, input = {}) => request(`/api/projects/${projectId}/render-jobs/${renderJobId}/delivery-packages`, { method: "POST", body: JSON.stringify(input) }),
  deliveryPackages: (projectId, renderJobId = "") => request(`/api/projects/${projectId}/delivery-packages${renderJobId ? `?renderJobId=${encodeURIComponent(renderJobId)}` : ""}`),
  cancelRenderJob: (projectId, renderJobId) => request(`/api/projects/${projectId}/render-jobs/${renderJobId}/cancel`, { method: "POST", body: "{}" }),
  assets: (projectId) => request(`/api/projects/${projectId}/assets`),
  createAsset: (projectId, input) => request(`/api/projects/${projectId}/assets`, { method: "POST", body: JSON.stringify(input) }),
  addAssetVersion: (projectId, assetId, input) => request(`/api/projects/${projectId}/assets/${assetId}/versions`, { method: "POST", body: JSON.stringify(input) }),
};
